import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {
  assertDiskSpace, badRequest, conflict, ensureDirectory, fileSize, removeSidecars,
  syncDirectory, unavailable, validateStagedDatabase, verifyDatabaseFile
} from '../restore/databaseFile.js';
import { CONFIRMATION_PHRASE, safetyBackupsKept } from '../restore/restoreConfig.js';

/*
  Restoring a backup replaces the whole inventory, so the sequence is deliberately defensive:
  an upload is streamed to a private staging file, validated there, and only a validated copy is
  swapped in — after a verified safety backup of the current database has been written. Any failure
  after the swap starts rolls the safety backup back before the request is answered.

  This service also owns the maintenance state the rest of the application asks about: while a
  restore runs, writes are refused and a backup download may not overlap the swap.
*/
export class RestoreService {
  constructor({ db, database, staging, dataDir, safetyBackupDir }) {
    this.db = db;
    // The connection lifecycle of the active database, kept behind the two calls used here.
    this.database = database;
    this.staging = staging;
    this.dataDir = dataDir;
    this.safetyBackupDir = safetyBackupDir;
    this.restoreRunning = false;
    this.backupsInFlight = 0;
    this.criticalFailure = null;
  }

  isMaintenance() {
    return this.restoreRunning || this.criticalFailure !== null;
  }

  status() {
    return {
      ready: !this.isMaintenance(),
      restoring: this.restoreRunning,
      critical: this.criticalFailure !== null
    };
  }

  beginBackupDownload() {
    if (this.restoreRunning) throw unavailable('A backup is being restored. Try the download again in a moment.');
    this.backupsInFlight += 1;
  }

  endBackupDownload() {
    this.backupsInFlight = Math.max(0, this.backupsInFlight - 1);
  }

  async waitForBackupDownloads() {
    for (let attempt = 0; this.backupsInFlight > 0 && attempt < 100; attempt++) {
      await new Promise(resolve => setTimeout(resolve, 50));
    }
    if (this.backupsInFlight > 0) throw conflict('A backup download is still running. Try again in a moment.');
  }

  // First stage: the streamed upload is described back to the user and becomes a staged session.
  validateUpload(file) {
    this.staging.sweepExpired();
    try {
      const summary = validateStagedDatabase(file.path);
      // The original name is only echoed back; the staged path is generated by the server.
      return this.staging.create(file.path, summary, file.originalname, file.size);
    } catch (error) {
      // A rejected upload never stays on disk.
      this.staging.discardUpload(file.path);
      throw error;
    }
  }

  safetyBackupName() {
    const stamp = `${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}Z`;
    const base = `pre-restore-${stamp}`;
    if (!fs.existsSync(path.join(this.safetyBackupDir, `${base}.sqlite`))) return `${base}.sqlite`;
    return `${base}-${crypto.randomBytes(2).toString('hex')}.sqlite`;
  }

  // Retention: the newest safetyBackupsKept copies are kept. Cleanup never touches the copy written
  // by the running restore, and a failing cleanup never fails the restore.
  pruneSafetyBackups(keep) {
    try {
      const files = fs.readdirSync(this.safetyBackupDir)
        .filter(name => name.startsWith('pre-restore-') && name.endsWith('.sqlite') && name !== keep)
        .sort();
      for (const name of files.slice(0, Math.max(0, files.length + 1 - safetyBackupsKept))) {
        fs.rmSync(path.join(this.safetyBackupDir, name), { force: true });
      }
    } catch (error) {
      console.error('[restore] safety backup cleanup failed', error);
    }
  }

  rollback(safetyPath) {
    try { this.database.close(); } catch { /* the connection may already be gone */ }
    removeSidecars(this.database.path);
    fs.copyFileSync(safetyPath, this.database.path);
    this.database.open();
    verifyDatabaseFile(this.database.path, 'The recovered database failed verification.');
    this.db.prepare('SELECT COUNT(*) AS count FROM items').get();
  }

  counts() {
    return {
      categories: this.db.prepare('SELECT COUNT(*) AS count FROM categories').get().count,
      items: this.db.prepare('SELECT COUNT(*) AS count FROM items').get().count,
      fields: this.db.prepare('SELECT COUNT(*) AS count FROM custom_fields').get().count,
      fieldValues: this.db.prepare('SELECT COUNT(*) AS count FROM item_field_values').get().count,
      photos: this.db.prepare('SELECT COUNT(*) AS count FROM item_photos').get().count
    };
  }

  // Second stage: the short-lived single-use token plus the explicit confirmation phrase.
  async apply(token, confirmation) {
    if (this.criticalFailure) throw unavailable('The application is in a failed restore state and needs manual recovery.');
    if (confirmation !== CONFIRMATION_PHRASE) throw badRequest(`Type ${CONFIRMATION_PHRASE} to confirm that current data will be replaced.`);
    if (typeof token !== 'string' || !token) throw badRequest('A validated backup is required. Validate the file again.');
    this.staging.sweepExpired();
    if (!this.staging.has(token)) throw badRequest('The restore session is unknown or has expired. Validate the file again.');
    if (this.restoreRunning) throw conflict('Another restore is already running.');

    this.restoreRunning = true;
    const stagedFile = this.staging.claim(token).file;
    const databasePath = this.database.path;
    let safetyPath = null;
    let swapStarted = false;
    try {
      await this.waitForBackupDownloads();
      if (!fs.existsSync(stagedFile)) throw badRequest('The staged backup is no longer available. Validate the file again.');
      // The staged file is checked once more so nothing can have changed since validation.
      const summary = validateStagedDatabase(stagedFile);

      ensureDirectory(this.safetyBackupDir);
      assertDiskSpace(this.dataDir, fileSize(databasePath) + fileSize(stagedFile) + 16 * 1024 * 1024);
      safetyPath = path.join(this.safetyBackupDir, this.safetyBackupName());
      await this.db.backup(safetyPath);
      verifyDatabaseFile(safetyPath, 'The safety backup of the current database failed verification.', true);

      // The candidate sits next to the active database so the final replacement is an atomic rename.
      const candidatePath = path.join(this.dataDir, `restore-candidate-${crypto.randomBytes(8).toString('hex')}.sqlite`);
      try {
        fs.copyFileSync(stagedFile, candidatePath);
        fs.chmodSync(candidatePath, 0o600);
        verifyDatabaseFile(candidatePath, 'The prepared database failed verification before replacement.', true);

        // Test-only hook: widens the maintenance window so a concurrent write can be observed.
        const delay = Number(process.env.RESTORE_TEST_DELAY_MS) || 0;
        if (delay) await new Promise(resolve => setTimeout(resolve, delay));

        swapStarted = true;
        this.database.close();
        // Stale journals of the replaced database must never be attached to the restored one.
        removeSidecars(databasePath);
        fs.renameSync(candidatePath, databasePath);
        syncDirectory(this.dataDir);
      } finally {
        fs.rmSync(candidatePath, { force: true });
      }

      // Test-only hook: proves that a failure after the swap rolls the safety backup back.
      if (process.env.RESTORE_TEST_FAILURE === 'after-swap') throw new Error('Simulated restore failure after the swap.');

      this.database.open();
      verifyDatabaseFile(databasePath, 'The restored database failed verification.');
      if (this.db.pragma('foreign_key_check').length) throw new Error('The restored database contains broken relationships.');
      const restored = this.counts();

      this.staging.discardUpload(stagedFile);
      this.pruneSafetyBackups(path.basename(safetyPath));
      return { summary: { ...summary, ...restored }, safety_backup: path.basename(safetyPath) };
    } catch (error) {
      console.error('[restore] restore failed', error);
      this.staging.discardUpload(stagedFile);
      if (!swapStarted) throw error.status ? error : badRequest('The backup could not be restored. The current data was not changed.');
      try {
        this.rollback(safetyPath);
      } catch (recoveryError) {
        // Nothing is deleted here: every recoverable file stays on disk for manual recovery.
        this.criticalFailure = { safetyPath, at: new Date().toISOString() };
        console.error(`[restore] CRITICAL: rollback failed. Safety backup kept at ${safetyPath}, active database at ${databasePath}`, recoveryError);
        throw Object.assign(new Error('The restore failed and the previous database could not be recovered automatically. The application is stopped for writes; recover the pre-restore backup manually.'), { status: 500 });
      }
      throw Object.assign(new Error('The restore failed and the previous database was recovered. No data was lost.'), { status: 500 });
    } finally {
      this.restoreRunning = false;
    }
  }
}
