import fs from 'node:fs';
import path from 'node:path';
import {
  assertDiskSpace, badRequest, fileSize, validateStagedDatabase, verifyDatabaseFile
} from '../restore/databaseFile.js';
import { CONFIRMATION_PHRASE, safetyBackupsKept } from '../restore/restoreConfig.js';

/*
  Restoring a backup replaces the whole inventory, so the sequence is deliberately defensive:
  an upload is streamed to a private staging file, validated there, and only a validated copy is
  swapped in — after a verified safety backup of the current database has been written. Any failure
  after the swap starts rolls the safety backup back before the request is answered.

  The maintenance state, the safety backup, the swap, and the rollback are shared with the inventory
  reset and live in DatabaseMaintenance; this service decides what is swapped in.
*/
export class RestoreService {
  constructor({ db, maintenance, staging, dataDir, safetyBackupDir }) {
    this.db = db;
    this.maintenance = maintenance;
    this.staging = staging;
    this.dataDir = dataDir;
    this.safetyBackupDir = safetyBackupDir;
  }

  // First stage: the streamed upload is described back to the user and becomes a staged session.
  validateUpload(file) {
    this.staging.sweepExpired();
    try {
      const summary = validateStagedDatabase(file.path);
      // The original name is only echoed back; the staged path is generated by the server.
      return this.staging.create(file.path, summary, file.originalname, file.size);
    } catch (error) {
      // A rejected upload never stays on disk.
      this.staging.discardUpload(file.path);
      throw error;
    }
  }

  // Retention: the newest safetyBackupsKept copies are kept. Cleanup never touches the copy written
  // by the running restore, and a failing cleanup never fails the restore.
  pruneSafetyBackups(keep) {
    try {
      const files = fs.readdirSync(this.safetyBackupDir)
        .filter(name => name.startsWith('pre-restore-') && name.endsWith('.sqlite') && name !== keep)
        .sort();
      for (const name of files.slice(0, Math.max(0, files.length + 1 - safetyBackupsKept))) {
        fs.rmSync(path.join(this.safetyBackupDir, name), { force: true });
      }
    } catch (error) {
      console.error('[restore] safety backup cleanup failed', error);
    }
  }

  counts() {
    return {
      categories: this.db.prepare('SELECT COUNT(*) AS count FROM categories').get().count,
      items: this.db.prepare('SELECT COUNT(*) AS count FROM items').get().count,
      fields: this.db.prepare('SELECT COUNT(*) AS count FROM custom_fields').get().count,
      fieldValues: this.db.prepare('SELECT COUNT(*) AS count FROM item_field_values').get().count,
      photos: this.db.prepare('SELECT COUNT(*) AS count FROM item_photos').get().count
    };
  }

  // Second stage: the short-lived single-use token plus the explicit confirmation phrase.
  async apply(token, confirmation) {
    this.maintenance.assertRecoverable();
    if (confirmation !== CONFIRMATION_PHRASE) throw badRequest(`Type ${CONFIRMATION_PHRASE} to confirm that current data will be replaced.`);
    if (typeof token !== 'string' || !token) throw badRequest('A validated backup is required. Validate the file again.');
    this.staging.sweepExpired();
    if (!this.staging.has(token)) throw badRequest('The restore session is unknown or has expired. Validate the file again.');
    this.maintenance.acquire('restore');

    const stagedFile = this.staging.claim(token).file;
    const databasePath = this.maintenance.database.path;
    let safetyPath = null;
    let swapStarted = false;
    try {
      await this.maintenance.waitForBackupDownloads();
      if (!fs.existsSync(stagedFile)) throw badRequest('The staged backup is no longer available. Validate the file again.');
      // The staged file is checked once more so nothing can have changed since validation.
      const summary = validateStagedDatabase(stagedFile);

      assertDiskSpace(this.dataDir, fileSize(databasePath) + fileSize(stagedFile) + 16 * 1024 * 1024);
      safetyPath = await this.maintenance.writeSafetyBackup(this.safetyBackupDir, 'pre-restore');

      const candidatePath = this.maintenance.candidatePath('restore-candidate');
      try {
        fs.copyFileSync(stagedFile, candidatePath);
        fs.chmodSync(candidatePath, 0o600);
        verifyDatabaseFile(candidatePath, 'The prepared database failed verification before replacement.', true);
        await this.maintenance.testPause();

        swapStarted = true;
        this.maintenance.swapIn(candidatePath);
      } finally {
        fs.rmSync(candidatePath, { force: true });
      }

      this.maintenance.testFailure('after-swap');
      this.maintenance.reopenAndVerify('The restored database failed verification.');
      const restored = this.counts();

      this.staging.discardUpload(stagedFile);
      this.pruneSafetyBackups(path.basename(safetyPath));
      return { summary: { ...summary, ...restored }, safety_backup: path.basename(safetyPath) };
    } catch (error) {
      console.error('[restore] restore failed', error);
      this.staging.discardUpload(stagedFile);
      if (!swapStarted) throw error.status ? error : badRequest('The backup could not be restored. The current data was not changed.');
      this.maintenance.recover(safetyPath, 'The restore failed and the previous database could not be recovered automatically. The application is stopped for writes; recover the pre-restore backup manually.');
      throw Object.assign(new Error('The restore failed and the previous database was recovered. No data was lost.'), { status: 500 });
    } finally {
      this.maintenance.release();
    }
  }
}
